spring:
  application:
    name: spring-boot-sentinel
  redis:
    password:
    sentinel:
      master: mymaster
      nodes: 127.0.0.1:26379
    timeout: 10000
    keyPrefix: 'RD:'
    jedis:
      pool:
        max-active: 150
        max-idle: 10
        min-idle: 1
        max-wait: 3000
        time-between-eviction-runs: 50
