spring:
  application:
    name: spring-boot-jedis
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 150
        max-idle: 10
        min-idle: 1
        max-wait: 3000
        time-between-eviction-runs: 50
    timeout: 1000
